feature/11735_api_guardian
flash-global/payment-client pull request #10
Opened 2018-09-26 15:55 UTC by skrijeljhasib

Update vendors

2018-09-26 16:37 UTC, lvenier approved these changes
$payer->setAuthorization('toto');
:-1:

2018-09-26 17:37 UTC, Zenzumai commented
Sérieux? c'est quoi payer ?

2018-10-03 07:34 UTC, CaillaudPA approved these changes

2018-10-04 07:27 UTC, mtisserant commented on src/Payer.php
>  use Fei\ApiClient\AbstractApiClient;
why not using AbstractApiClient from fei/api-client ?

2018-10-04 07:28 UTC, mtisserant requested changes
use if possible abstractApiClient from fei/api-client package

2018-10-04 07:56 UTC, mtisserant commented on src/Payer.php
> +            $request->addHeader('Authorization', $this->getAuthorization());
this code is already write in send method of AbstractApiClient

2018-10-04 07:59 UTC, mtisserant approved these changes

2019-07-02 16:55 UTC, closed without merging